import './globals.css'
import type {Metadata} from 'next'
import {Open_Sans} from 'next/font/google'
import Header from "@/compoent/Header";
import AuthContext from "@/context/AuthContext";

const openSans = Open_Sans({subsets: ['latin']})

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <>
            <html lang="en" className={openSans.className}>
            <body className='flex flex-col w-full max-w-screen-md mx-auto overflow-auto'>
            <AuthContext>
                <header className='sticky top-0 bg-white z-10 border-b'>
                    <Header/>
                </header>
                <main className='grow'>{children}</main>
            </AuthContext>
            </body>
            </html>
        </>

    )
}
